### ISSUE TITLE
Help for [OSError: [Errno 99] Cannot assign requested address]

### ISSUE THREAD

**Issue by robotsaklar** [dennorske/samp-packet-proxy#16]
Proxy is listening on port 25565 for SAMP server 157.254.166.76 using port 7777
Traceback (most recent call last):
  File "/home/robotsaklar/samp-packet-proxy/pack_scan.py", line 215, in <module>
    proxy = UDPServer(bind_address, target_address)
  File "/home/robotsaklar/samp-packet-proxy/pack_scan.py", line 74, in __init__
    self.server = socketserver.UDPServer(
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 99] Cannot assign requested address

**Comment by dennorske** [comment]
Hello, make sure you run as root, or more specifically give access to bind to network ports.
