### ISSUE TITLE
Help still not working, do u have acontact?

### ISSUE THREAD

**Issue by en1gm411** [dennorske/samp-packet-proxy#17]
# python3 test_pack_scan.py 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg/__init__.py", line 145, in __makeattr
    modpath, attrname = self.__map__[name]
                        ~~~~~~~~~~~~^^^^^^
KeyError: '__spec__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zzz/tools/samp-packet-proxy/test_pack_scan.py", line 9, in <module>
    import pytest
  File "/usr/lib/python3/dist-packages/pytest/__init__.py", line 5, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/usr/lib/python3/dist-packages/_pytest/assertion/__init__.py", line 9, in <module>
    from _pytest.assertion import rewrite
  File "/usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py", line 34, in <module>
    from _pytest.assertion import util
  File "/usr/lib/python3/dist-packages/_pytest/assertion/util.py", line 13, in <module>
    import _pytest._code
  File "/usr/lib/python3/dist-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code
  File "/usr/lib/python3/dist-packages/_pytest/_code/code.py", line 54, in <module>
    class Code:
  File "/usr/lib/python3/dist-packages/_pytest/_code/code.py", line 81, in Code
    def path(self) -> Union[py.path.local, str]:
                            ^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg/__init__.py", line 152, in __makeattr
    result = importobj(modpath, attrname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg/__init__.py", line 72, in importobj
    module = __import__(modpath, None, None, ['__doc__'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1136, in _find_and_load_unlocked
  File "/usr/lib/python3/dist-packages/py/_vendored_packages/apipkg/__init__.py", line 150, in __makeattr
    raise AttributeError(name)
AttributeError: __spec__

**Comment by dennorske** [comment]
You did not follow the instructions :) 

`test_pack_scan.py` is to _test_ the code, not the proxy.

Read the readme.md carefully, and see how it is done there :)
